version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: 'service_healthy'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A core worker --loglevel=INFO --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: 'service_healthy'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7.0.11-alpine

volumes:
  postgres_data:
