version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: 'service_healthy'
    env_file:
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    volumes:
      - .:/code
    depends_on:
      db:
        condition: 'service_healthy'
    env_file:
      - .env

  redis:
    image: redis:7.0.11-alpine

volumes:
  postgres_data:
