# Generated by Django 4.2.7 on 2024-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
