# Generated by Django 5.0 on 2023-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_created_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo",
            field=models.DateField(max_length=2000),
        ),
    ]
