# Generated by Django 4.2.7 on 2024-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_category_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
