# Generated by Django 5.0 on 2023-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todo_created_alter_todo_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo",
            field=models.CharField(max_length=2000),
        ),
    ]
